trigger:
- nightly/*

jobs:
  - job: catalina
    timeoutInMinutes: 150
    displayName: "Bottle for macOS 10.15 (Catalina)"
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - script: .ci/bottle-formula-from-branch.sh
        displayName: Bottle formula on 10.15
        env:
          OS: '10.15'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_BINTRAY_USER: dciabrin
          HOMEBREW_BINTRAY_KEY: $(BINTRAY_KEY)
      - script: cp *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_catalina

  - job: mojave
    timeoutInMinutes: 150
    dependsOn: catalina
    displayName: "Bottle for macOS 10.14 (Mojave)"
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - download: current
        artifact: post_catalina
      - script: cp $(Pipeline.Workspace)/post_catalina/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: .ci/bottle-formula-from-branch.sh
        displayName: Bottle formula on 10.14
        env:
          OS: '10.14'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_BINTRAY_USER: dciabrin
          HOMEBREW_BINTRAY_KEY: $(BINTRAY_KEY)
      - script: cp git-bottle-sha.diff *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_mojave

  - job: publish
    dependsOn: mojave
    displayName: "Publish new version and bottles"
    pool:
      vmImage: 'macOS-10.15'
    steps:
      - checkout: self
        persistCredentials: true
      - download: current
        artifact: post_mojave
      - script: cp $(Pipeline.Workspace)/post_mojave/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: |
          patch -p1 < $(Pipeline.Workspace)/post_mojave/git-bottle-sha.diff
          git add Formula/*.rb
          git commit --amend --no-edit
        displayName: Restore bottle hashes from previous job in git
      - script: .ci/publish-bottles.sh
        displayName: Publish new bottles
        env:
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_BINTRAY_USER: dciabrin
          HOMEBREW_BINTRAY_KEY: $(BINTRAY_KEY)
      - script: .ci/publish-new-formula-version.sh
        displayName: Publish new Formula version
        env:
          BRANCH: $(Build.SourceBranch)
      - script: |
          branch=`echo $BRANCH | sed 's%refs/heads/%%'`
          pkg=`.ci/pkg-name-from-branch.sh $branch`
          .ci/gc-nightly-branches.sh -u dciabrin -r emudbg -b '^refs/heads/nightly/'"$pkg"'-[0-9]*'
        displayName: Clean up old nightly branches
        env:
          BRANCH: $(Build.SourceBranch)
          GH_TOKEN: $(GH_TOKEN)
