trigger:
- nightly/*

jobs:
  - job: monterey
    timeoutInMinutes: 150
    displayName: "Bottle for macOS 12 (Monterey)"
    pool:
      vmImage: 'macOS-12'
    steps:
      - script: |
          pushd "$(brew --repo)" && git fetch && git reset --hard origin/master && popd
          .ci/setup-brew-environment.sh
          .ci/bottle-formula.sh
        displayName: Bottle formula on 12
        env:
          OS: '12'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
      - script: cp *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_monterey

  - job: bigsur
    timeoutInMinutes: 150
    dependsOn: monterey
    displayName: "Bottle for macOS 11 (Big Sur)"
    pool:
      vmImage: 'macOS-11'
    steps:
      - download: current
        artifact: post_monterey
      - script: cp $(Pipeline.Workspace)/post_monterey/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: |
          pushd "$(brew --repo)" && git fetch && git reset --hard origin/master && popd
          .ci/setup-brew-environment.sh
          .ci/bottle-formula.sh
        displayName: Bottle formula on 11
        env:
          OS: '11'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
      - script: cp git-bottle-sha.diff *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_bigsur

  - job: publish
    dependsOn: bigsur
    displayName: "Publish new version and bottles"
    pool:
      vmImage: 'macOS-12'
    steps:
      - checkout: self
        persistCredentials: true
      - download: current
        artifact: post_bigsur
      - script: cp $(Pipeline.Workspace)/post_bigsur/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: |
          patch -p1 < $(Pipeline.Workspace)/post_bigsur/git-bottle-sha.diff
        displayName: Restore bottle hashes from previous job in git
      # Publishing the new version prior to the bottles, because
      # the bottle are bundled in a github archive which comes
      # with a new tag in the git repo. So all the patches must be
      # prior to the bottles.
      - script: .ci/publish-new-formula-version.sh
        displayName: Publish new Formula version
        env:
          BRANCH: $(Build.SourceBranch)
      # Until bottles are published, there's a small time window
      # where 'brew install <pkg>' won't find bottles and rebuild
      # from source. The inconvenience is assumed to be minimal.
      - script: .ci/publish-new-formula-bottles.sh
        displayName: Publish new bottles
        env:
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
