trigger:
- nightly/*

jobs:
  - job: monterey
    timeoutInMinutes: 150
    displayName: "Bottle for macOS 12 (Monterey)"
    pool:
      vmImage: 'macOS-12'
    steps:
      - script: |
          pushd "$(brew --repo)" && git fetch && git reset --hard origin/master && popd
          .ci/setup-brew-environment.sh
          .ci/bottle-formula-from-branch.sh
        displayName: Bottle formula on 12
        env:
          OS: '12'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
      - script: cp *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_monterey

  - job: bigsur
    timeoutInMinutes: 150
    dependsOn: monterey
    displayName: "Bottle for macOS 11 (Big Sur)"
    pool:
      vmImage: 'macOS-11'
    steps:
      - download: current
        artifact: post_monterey
      - script: cp $(Pipeline.Workspace)/post_monterey/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: |
          pushd "$(brew --repo)" && git fetch && git reset --hard origin/master && popd
          .ci/setup-brew-environment.sh
          .ci/bottle-formula-from-branch.sh
        displayName: Bottle formula on 11
        env:
          OS: '11'
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
      - script: cp git-bottle-sha.diff *.bottle.json *.bottle*.tar.gz $(Build.ArtifactStagingDirectory)/
        displayName: Capture built bottles for next job
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: post_bigsur

  - job: publish
    dependsOn: bigsur
    displayName: "Publish new version and bottles"
    pool:
      vmImage: 'macOS-12'
    steps:
      - checkout: self
        persistCredentials: true
      - download: current
        artifact: post_bigsur
      - script: cp $(Pipeline.Workspace)/post_bigsur/*.bottle.* $PWD/
        displayName: Retrieve previously built bottles
      - script: |
          patch -p1 < $(Pipeline.Workspace)/post_bigsur/git-bottle-sha.diff
          git add Formula/*.rb
          git commit --amend --no-edit
        displayName: Restore bottle hashes from previous job in git
      - script: .ci/publish-bottles.sh
        displayName: Publish new bottles
        env:
          BRANCH: $(Build.SourceBranch)
          HOMEBREW_GITHUB_API_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
      - script: .ci/publish-new-formula-version.sh
        displayName: Publish new Formula version
        env:
          BRANCH: $(Build.SourceBranch)
      - script: |
          branch=`echo $BRANCH | sed 's%refs/heads/%%'`
          pkg=`.ci/pkg-name-from-branch.sh $branch`
          repo=`echo "$pkg" | sed 's/^ngdevkit-gngeo/gngeo/'`
          .ci/gc-nightly-branches.sh -u dciabrin -r "$repo" -b '^refs/heads/nightly/'"$pkg"'-[0-9]*'
        displayName: Clean up old nightly branches
        env:
          BRANCH: $(Build.SourceBranch)
          GH_TOKEN: $(GH_TOKEN)
