trigger:
  branches:
    include:
    - master
  paths:
    include:
    - Formula

jobs:
  - job: rmbottles
    displayName: "Remove old ngdevkit bottles"
    pool:
      vmImage: 'macOS-latest'
    steps:
      - script: .ci/gc-projects-nightly-bottles.sh
        displayName: Remove old ngdevkit bottles
        env:
          GH_TOKEN: $(HOMEBREW_GITHUB_API_TOKEN)
