name: Clean up old published bottles
on:
  push:
    branches:
      - 'master'
    paths:
      - 'Formula/**'

jobs:
  rmbottles:
    name: "Remove old ngdevkit bottles"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove old ngdevkit bottles
        run: .ci/gc-projects-nightly-bottles.sh
